### ISSUE TITLE
Day Planner

### ISSUE THREAD

**Issue by Lee1887** [Lee1887/capstone-project#1]
## Value Proposition

**As a** User
**I need** a Daily Planner
**to be able to** organize my day

## Description

![Bildschirmfoto 2022-07-20 um 16 10 58](https://user-images.githubusercontent.com/106076920/180003769-ae12bdf9-7ba5-4a13-b375-3b445f9d0623.png)

Scribble / design or text

## Acceptance Criteria

- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ]  
## Tasks

(for developers team)

- [ ] Global Styles
- [ ] connect with component/BulletJournal/BulletJournalDayPlanner
- [ ] component/DayPlanner
- [ ] Storybook
- [ ] Write tests
- [ ] Create db.js with Cards
- [ ] Add to App

**Comment by stefankorder** [comment]
How much time do you think you will need for this userstory?

**Comment by PReichetanz** [comment]
Hi Luca,

a really good start for your app and the user story! 🎉

Just two things:
- Why do you start at 5 and end at 9, what about all the other hours of the day?
- Do you hardcode the data for "Zähne putzen", "Essen", and "Sport" or is there a separate file with mock data?

@stefankorder We agreed to leave the complexity / necessary time out of the user story.

**Comment by Lee1887** [comment]
@stefankorder In terms of time, I anticipate that I will need around 2-3 days.
I absolutely want to finish it by Sunday.
But it is also possible.
The design will most likely be the most difficult component for me.

**Comment by stefankorder** [comment]
@PReichetanz I asked for the time because i think the user story could be to big.

**Comment by Lee1887** [comment]
I mean 2-3 days for all three user stories.
Which of these are on the Day Planner. @stefankorder However, that is a big user story.
