### ISSUE TITLE
Lists 2

### ISSUE THREAD

**Issue by Lee1887** [Lee1887/capstone-project#10]
## Value Proposition

**As a** User
**I need** Lists
**to be able to** notice everything

## Description

<img width="400" alt="Lists 2" src="https://user-images.githubusercontent.com/106076920/181214763-99d890e8-95f5-4128-86b5-db366425308d.png">

Scribble / design or text

## Acceptance Criteria

- [ ] The example calls up a list in the right box.
- [ ] A search bar is located at the top of each list.
- [ ] You can look for a task there if the list is too big.
- [ ] The list name is listed underneath.
- [ ] New tasks can be added using the "Add a new task" link below that.

## Tasks

(for developers team)

- [ ] Global Styles
- [ ] connect with component/Specials
- [ ] component/List
- [ ] Storybook
- [ ] Write tests
- [ ] Create db.js with Cards
- [ ] Add to App
