### ISSUE TITLE
Lists #3

### ISSUE THREAD

**Issue by Lee1887** [Lee1887/capstone-project#11]
## Value Proposition

**As a** User
**I need** Lists
**to be able to** notice everything

## Description

<img width="400" alt="Lists 3" src="https://user-images.githubusercontent.com/106076920/181216927-f4cd44a3-a28d-4339-b0aa-35d10203adbf.png">

Scribble / design or text

## Acceptance Criteria

- [ ] There are 3 dots placed after the list name.
- [ ] Edit and delete just once.
- [ ] The list name can be entered or modified using Edit.
- [ ] Delete eliminates the list.
- [ ] It is necessary to confirm this procedure first, though. 

## Tasks

(for developers team)

- [ ] Global Styles
- [ ] connect with component/Specials
- [ ] component/List
- [ ] Storybook
- [ ] Write tests
- [ ] Create db.js with Cards
- [ ] Add to App
