### ISSUE TITLE
Lists #4

### ISSUE THREAD

**Issue by Lee1887** [Lee1887/capstone-project#12]
## Value Proposition

**As a** User
**I need** Lists
**to be able to** notice everything

## Description

<img width="400" alt="Lists 4" src="https://user-images.githubusercontent.com/106076920/181219111-62624d30-3263-4dd2-a4f6-3e3615c06dd0.png">

Scribble / design or text

## Acceptance Criteria

- [ ]New tasks can be added using the "Add a new Task" form.
- [ ] A circle, a text space, and a form for entering the date are all visible at the top.
- [ ] The "Add a new Task" form is always located beneath the tasks. 

## Tasks

(for developers team)

- [ ] Global Styles
- [ ] connect with component/Specials
- [ ] component/List
- [ ] Storybook
- [ ] Write tests
- [ ] Create db.js with Cards
- [ ] Add to App
