### ISSUE TITLE
Day Planner #1

### ISSUE THREAD

**Issue by Lee1887** [Lee1887/capstone-project#2]
## Value Proposition

**As a** User
**I need** a Daily Planner
**to be able to** organize my day

## Description

![Bildschirmfoto 2022-07-20 um 16 10 58](https://user-images.githubusercontent.com/106076920/180003769-ae12bdf9-7ba5-4a13-b375-3b445f9d0623.png)

Scribble / design or text

## Acceptance Criteria

- [ ] In my project, the header reads "Day Planner."
- [ ] The time is shown in blue on the body and begins at 05.00 and concludes at 09:00.
- [ ] The grey boxes represent the actions that occur at that time. 

## Tasks

(for developers team)

- [ ] Global Styles
- [ ] connect with component/BulletJournal/BulletJournalDayPlanner
- [ ] component/DayPlanner
- [ ] Storybook
- [ ] Write tests
- [ ] Create db.js with Cards
[ ] Add to App
