### ISSUE TITLE
Day Planner + Actually Date

### ISSUE THREAD

**Issue by Lee1887** [Lee1887/capstone-project#2]
## Value Proposition

**As a** User
**I need** a Daily Planner
**to be able to** organize my day

## Description

![Bildschirmfoto 2022-07-20 um 16 11 04](https://user-images.githubusercontent.com/106076920/180008089-8de3603e-8df9-4510-92ae-86507867ffdb.png)

Scribble / design or text

## Acceptance Criteria

- [ ] Under the title, the current date is displayed.
- [ ] The body is separated into three distinct box colors.
        Grey, blue, and green colors.
- [ ] The grey boxes indicate that the dates are past.
- [ ] The blue box shows that the time is now.
- [ ] The forthcoming dates are shown by the green boxes. 
## Tasks

(for developers team)

- [ ] Global Styles
- [ ] connect with component/BulletJournal/BulletJournalDayPlanner
- [ ] component/DayPlanner
- [ ] Storybook
- [ ] Write tests
- [ ] Create db.js with Cards
- [ ] Add to App

**Comment by actyvystom** [comment]
Hi Luca,
this one looks already quite nice :)

A few comments to consider: 
- Your value proposition statement is a bit blurry, also your title. I suggest clarifying this by adjusting the title to e.g. _Currrent day view/screen_ and adjusting the proposition statement accordingly: as a user I need an overview of the current day so that I have an idea of what to do next and which tasks/plan items have already passed.

Acceptance criteria and development tasks look fine, though you could point out more detail on Storybook and testing (which components in storybook, tests for which components).
