### ISSUE TITLE
Daily Planner + navigation

### ISSUE THREAD

**Issue by Lee1887** [Lee1887/capstone-project#3]
## Value Proposition

**As a** User
**I need** a Daily Planner
**to be able to** organize my day

## Description

<img width="366" alt="Bildschirmfoto 2022-07-20 um 16 45 37" src="https://user-images.githubusercontent.com/106076920/180011777-8b855eee-08cf-486e-907e-479f8be46766.png">

Scribble / design or text

## Acceptance Criteria

- [ ] Add a navbar with the properties Home and Bullet Journal.

## Tasks

(for developers team)

- [ ] Global Styles
- [ ] connect with component/BulletJournal/BulletJournalDayPlanner
- [ ] component/DayPlanner
- [ ] Storybook
- [ ] Write tests
- [ ] Create db.js with Cards
- [ ] Add to App
