### ISSUE TITLE
Day Planner #3

### ISSUE THREAD

**Issue by Lee1887** [Lee1887/capstone-project#4]
## Value Proposition

**As a** User
**I need** a Daily Planner
**to be able to** organize my day

## Description

<img width="366" alt="Bildschirmfoto 2022-07-20 um 16 45 37" src="https://user-images.githubusercontent.com/106076920/180011777-8b855eee-08cf-486e-907e-479f8be46766.png">

<img width="358" alt="Bildschirmfoto 2022-07-20 um 16 45 46" src="https://user-images.githubusercontent.com/106076920/180012697-77040554-1244-4522-839c-312767794f84.png">

Scribble / design or text

## Acceptance Criteria

- [ ] Add a navbar with the Home and Bullet Journal attributes.
- [ ] The grey boxes can be filled with content (currently "Placeholder input" is in there). 

## Tasks

(for developers team)

- [ ] Global Styles
- [ ] connect with component/BulletJournal/BulletJournalDayPlanner
- [ ] component/DayPlanner
- [ ] Storybook
- [ ] Write tests
- [ ] Create db.js with Cards
- [ ] Add to App
