### ISSUE TITLE
Week Planner #3

### ISSUE THREAD

**Issue by Lee1887** [Lee1887/capstone-project#7]
## Value Proposition

**As a** User
**I need** a Week Planner
**to be able to**organize my Week

## Description

Scribble / design or text

## Acceptance Criteria

- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 

## Tasks

(for developers team)

- [ ] Global Styles
- [ ] connect with component/BulletJournal/BulletJournalWeekPlanner
- [ ] component/WeekPlanner
- [ ] Storybook
- [ ] Write tests
- [ ] Create db.js with Cards
- [ ] Add to App
