### ISSUE TITLE
Week Planner #4

### ISSUE THREAD

**Issue by Lee1887** [Lee1887/capstone-project#8]
## Value Proposition

**As a** User
**I need** a Week Planner
**to be able to**organize my Week

## Description

<img width="400" alt="week2" src="https://user-images.githubusercontent.com/106076920/181001833-710f4fa7-a0fe-4c4b-9792-aac082f32b13.png">

Scribble / design or text

## Acceptance Criteria

- [ ] I
- [ ]
- [ ] 
- [ ] 

## Tasks

(for developers team)

- [ ] Global Styles
- [ ] connect with component/BulletJournalDayPlanner/BulletJournalWeekPlanner
- [ ] component/WeekPlanner
- [ ] Storybook
- [ ] Write tests
- [ ] Create db.js with Cards
- [ ] Add to App
