### ISSUE TITLE
Lists #1

### ISSUE THREAD

**Issue by Lee1887** [Lee1887/capstone-project#9]
## Value Proposition

**As a** User
**I need** Lists
**to be able to** notice everything

## Description

<img width="400" alt="Lists 1" src="https://user-images.githubusercontent.com/106076920/181210241-4ed4e19a-1379-453c-9e27-e21397a632ed.png">

Scribble / design or text

## Acceptance Criteria

- [ ] Build two boxes.
- [ ] A sort of menu bar is in the left box.
- [ ] "Overview, Lists, and add List" are the items listed there.
- [ ] In the menu bar, a huge number of lists may be inserted.

## Tasks

(for developers team)

- [ ] Global Styles
- [ ] connect with component/Specials
- [ ] component/List
- [ ] Storybook
- [ ] Write tests
- [ ] Create db.js with Cards
- [ ] Add to App
